apiVersion: v2
name: order-processing-service
description: Helm chart for Order Processing Service – Spring Boot Microservice on AKS
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Kumaraswami Hosuru
